### ISSUE TITLE
Q: Will it delete all my current wysiwyg content in the database ?

### ISSUE THREAD

**Issue by KeziahMoselle** [melishev/strapi-plugin-react-editorjs#1]
Hello,
this addon looks great !

I was wondering if i'm installing this, will it wipe all current wysiwyg data or will it work normally ?

**Comment by melishev** [comment]
@KeziahMoselle, thank you very much for your question!

This is really interesting, and I will study it shortly and inform you about the result.

**Comment by KeziahMoselle** [comment]
I did test it and I think it does not but the editor can't parse the markdown it says something like "Error JSON.parse at #" something like that ! @melishev

**Comment by melishev** [comment]
Yes, the editor will not be able to recognize the saved data from your regular Wysiwyg editor due to the fact that they save HTML, and this plugin saves the data in JSON. This is a feature of Editor.js, you can see how it works at this [link](https://editorjs.io). @KeziahMoselle

**Comment by KeziahMoselle** [comment]
Yep this was my guess, thank you for confirming @melishev ! Great job btw !

**Comment by melishev** [comment]
Nice to hear that, thank you for your star.

If you have any more questions, do not hesitate to write to me.
 @KeziahMoselle
