### ISSUE TITLE
Inline Link possible?

### ISSUE THREAD

**Issue by quansenB** [melishev/strapi-plugin-react-editorjs#12]
Hi,

First of all: Thank you for your amazing work.

We are trying to implement your plugin as part of our new CMS stack.

Is it currently possible to allow for inline links? Strikethrough would be the cherry on the top :)

How would I go about adding that?

Also is there any way to disable modules? Our Editors for example won't ever need to use the code option?

Thank you :)

**Comment by quansenB** [comment]
> Hi,
> 
> First of all: Thank you for your amazing work.
> 
> We are trying to implement your plugin as part of our new CMS stack.
> 
> Is it currently possible to allow for inline links? Strikethrough would be the cherry on the top :)
> 
> How would I go about adding that?
> 
> Also is there any way to disable modules? Our Editors for example won't ever need to use the code option?`
> 
> ` Thank you :)`

**Comment by melishev** [comment]
Hi @quansenB ,
Read the readme.md file. Everything is written there
For example, how to set up a plugin: https://github.com/melishev/strapi-plugin-react-editorjs#%EF%B8%8F-how-to-customize-editor-optional
