### ISSUE TITLE
Get the size of an Image in Request

### ISSUE THREAD

**Issue by Johannes-Schiel** [melishev/strapi-plugin-react-editorjs#16]
Hello, i realy like you Plug-In, thx for your work!

I have one question, is there a possibility to get the width and height of an image in the final request and not only the data url? (new with Strapi and editorjs)

**Comment by melishev** [comment]
Hello @Johannes-Schiel .

The plugin allows you to add Editor.js to Strapi without problems, the plugin is not responsible for the functionality of Editor.js.

Editor.js and its Image add-on allow you to add images to a post, and what width and height they will ultimately be determined only by you. Also, the image padding tells you whether the image is full-width or not.

**Comment by melishev** [comment]
@Johannes-Schiel 
Well, the bot didn't send out an automatic beta update message, so I do it. Please check if your issue is fixed in the [new beta version](https://github.com/melishev/strapi-plugin-react-editorjs/releases/tag/v2.0.0-beta.2)⚠️.
