### ISSUE TITLE
Beta - Strapi v4: Collection of responsive URL's in Image Tool

### ISSUE THREAD

**Issue by jaskipper** [melishev/strapi-plugin-react-editorjs#22]
@melishev - I see in issue #6 that there was a feature request to return a collection of responsive URL's in the Image Tool. 

I too would love this. Strapi automatically creates multiple images when uploading to the Media Library, and returns all of the links to those images for the featured image. This would be extremely useful in automatically creating responsive images on a site. I'm willing to dive in and figure out how to get this done if you are in agreement that it's a good idea.

**Comment by melishev** [comment]
@jaskipper - Well, I think that since several people want to see this feature, then it will not be superfluous

**Comment by melishev** [comment]
Well, the bot didn't send out an automatic beta update message, so I do it. Please check if your issue is fixed in the [new beta version](https://github.com/melishev/strapi-plugin-react-editorjs/releases/tag/v2.0.0-beta.2)⚠️.
