### ISSUE TITLE
Beta - Strapi v4: How to Customize Editor

### ISSUE THREAD

**Issue by jaskipper** [melishev/strapi-plugin-react-editorjs#24]
The README instructions do not work in Strapi v4 on how to customize editor. I'm working on figuring out how to get this working. Here are the docs for extending plugins in Strapi v4: https://docs.strapi.io/developer-docs/latest/development/plugins-extension.html

I've tried this, but is not working in the setup that I currently have. I haven't tried this with strapi-plugin-react-editorjs installed via npm/yarn. I currently have my setup with this plugin under `./src/plugins/strapi-plugin-react-editorjs`. Once the current pull request is merged, I will test out the instructions in the above doc and will report back.

**Comment by melishev** [comment]
Well, the instruction works, good job - @jaskipper
