### ISSUE TITLE
unable to close the image upload modal and field title is missing with starpi v4

### ISSUE THREAD

**Issue by ganeshmohanty** [melishev/strapi-plugin-react-editorjs#26]
node version : 14.16.0
npm version: 6.14.11
os: windows 10
Database: mySql 8.10
strapi-plugin-react-editorjs: 2.0.0-beta.1

**Comment by nourseofcourse** [comment]
Same problem here.

**Comment by jaskipper** [comment]
@ganeshmohanty @nourseofcourse. Sorry, I didn't see your comments here, as I'm not a maintainer of this project. However, see the below comment for how to get the updated changes until those changes are merged.

https://github.com/melishev/strapi-plugin-react-editorjs/issues/11#issuecomment-1063523065

**Comment by ganeshmohanty** [comment]
@jaskipper thanks for your reply. can you add one more step which is pull your pull request and merge it to beta branch else the image  modal and link will not work.

**Comment by jaskipper** [comment]
@ganeshmohanty - Actually, that step is not necessary if you download just the beta-v4 branch. I removed the first part of the instructions that referenced the main branch. I think that is what you must have done. If you clone with the below command, you only get the beta-v4 branch.

```
git clone --single-branch --branch beta-v4 https://github.com/jaskipper/strapi-plugin-react-editorjs.git
```

**Comment by melishev** [comment]
@jaskipper - Thanks for helping the community
@ganeshmohanty , @nourseofcourse - today or tomorrow, we will release a new update for the beta

**Comment by melishev** [comment]
@ganeshmohanty , @nourseofcourse 
Well, the bot didn't send out an automatic beta update message, so I do it. Please check if your issue is fixed in the [new beta version](https://github.com/melishev/strapi-plugin-react-editorjs/releases/tag/v2.0.0-beta.2)⚠️.

**Comment by melishev** [comment]
💥 Well guys, I've released the beta to the official release.
