### ISSUE TITLE
Multiple empty lines are ignored

### ISSUE THREAD

**Issue by dcakmak** [melishev/strapi-plugin-react-editorjs#35]
Is it the default behavior of Editor.js that no matter how many blank lines I save in the editor, it still only saves one newline?
Is there any way to set the spacing of the blocks via the editor or do I have to adjust that via css in the frontend?

**Comment by kgrosvenor** [comment]
@dcakmak  You can adjust the block spacing on the front end with CSS mostly

**Comment by melishev** [comment]
@dcakmak 
The main part of the work of Editor.js itself is determined by its developers, this plugin simply allows you to integrate it into Strapi. Your question would be more appropriate to post in the main Editor.js repository.

But in general, yes, it will be the right solution to solve your problem through CSS.
