### ISSUE TITLE
Image Upload not working

### ISSUE THREAD

**Issue by dcakmak** [melishev/strapi-plugin-react-editorjs#36]
When I try to upload an image via the editor or copy it from another website, I always get the error message "Couldn't upload image. Please try another."

Strapi Version: 4.1.7
Editor.js: 2.0.0

**Comment by nhvu1988** [comment]
It's responding `405 Method Not Allowed` from the request URL: http://localhost:1337/api/react-editorjs/image/byFile. Seem the plugin has the permission for public users' roles but not sure how to configure it for Strapi users.

**Comment by melishev** [comment]
Well, the last PR https://github.com/melishev/strapi-plugin-react-editorjs/pull/44 should solve your problem, thanks for the input - @nhvu1988
