### ISSUE TITLE
Embed and Link - This content is blocked

### ISSUE THREAD

**Issue by gregghawes** [melishev/strapi-plugin-react-editorjs#38]
I can't seem to get the embed or link functions to work. 
![Screenshot_1](https://user-images.githubusercontent.com/46755934/164240856-625fbd4c-6015-4bf2-af5c-af087ed0e42b.png)

The embed element just shows "This content is blocked. Contact the site owner to fix the issue." 

When I try to add a link, an error pops up saying "Couldn't fetch the link data" and I notice a 404 shows in the console. 

`http: GET /api/react-editorjs/link?url=https%3A%2F%2Fwww.google.co.uk%2F (1 ms) 404`

"@strapi/strapi": "4.1.7",
"strapi-plugin-react-editorjs": "^2.0.0"

**Comment by melishev** [comment]
@gregghawes did you follow the instructions to enable Link functionality?

**Comment by gregghawes** [comment]
I added the `'img-src': ['*'],` to middlewares.js. Are there other instructions that I am missing?

**Comment by gregghawes** [comment]
This is my middlewares.js
```
module.exports = [
  'strapi::errors',
  {
    name: 'strapi::security',
    config: {
      contentSecurityPolicy: {
        directives: {
          'img-src': ['*'],
        },
      }
    },
  },
  'strapi::cors',
  'strapi::poweredBy',
  'strapi::logger',
  'strapi::query',
  'strapi::body',
  'strapi::session',
  'strapi::favicon',
  'strapi::public',
];

````

**Comment by melishev** [comment]
Well, the last PR https://github.com/melishev/strapi-plugin-react-editorjs/pull/44 should solve your problem, thanks for the input - @nhvu1988
