### ISSUE TITLE
Image Tool: uploading failed because of ReferenceError: axios is not defined

### ISSUE THREAD

**Issue by Yurgeman** [melishev/strapi-plugin-react-editorjs#5]
An error occurs when trying to insert text with pictures from the buffer or when dragging an image into the editor field: 
```Image Tool: uploading failed because of ReferenceError: axios is not defined```

the download is successful only if you press + and select the file manually

**Comment by melishev** [comment]
@Yurgeman 
Well, the bot didn't send out an automatic beta update message, so I do it. Please check if your issue is fixed in the [new beta version](https://github.com/melishev/strapi-plugin-react-editorjs/releases/tag/v2.0.0-beta.2)⚠️.
